import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
const poppins = Poppins({ 
  weight: ["400", "700"],
  subsets: ["latin", "latin-ext"] 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}
      <Toaster />
      </body>
    </html>
  );
}
